title: David Jin
remote_theme: ankitsultana/researcher@gem

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_text: "Page design by Ankit Sultana adapted by David Jin"

sass:
    style: compressed
    sass_dir: _sass

nav:
  - name: "Contact"
    link: "contact"
