title: David Jin
remote_theme: ankitsultana/researcher@gem

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_text: |
Template designed by Ankit Sultana and adapted by David Jin. 
* <a href="https://www.linkedin.com/in/david-j-662b25161/" target="_blank">LinkedIn</a>
* <a href="https://github.com/dgitj" target="_blank">Github</a>



sass:
    style: compressed
    sass_dir: _sass

nav:
  - name: "Contact"
    link: "contact"
